### ISSUE TITLE
ProDe: Add FU from HDB segfaults...

### ISSUE THREAD

**Issue by pjaaskel** [cpc/tce#81]
```
#0  0x00007ffff322b428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff322d02a in __GI_abort () at abort.c:89
#2  0x00007ffff32732e8 in __malloc_assert (
    assertion=assertion@entry=0x7ffff33873d8 "(unsigned long) (size) >= (unsigned long) (nb)", 
    file=file@entry=0x7ffff3383bc5 "malloc.c", line=line@entry=3722, 
    function=function@entry=0x7ffff33879e8 <__func__.11734> "_int_malloc") at malloc.c:301
#3  0x00007ffff32789b3 in _int_malloc (av=av@entry=0x7ffff35bab20 <main_arena>, bytes=bytes@entry=72)
    at malloc.c:3722
#4  0x00007ffff327a184 in __GI___libc_malloc (bytes=72) at malloc.c:2913
#5  0x00007ffff3b6ce78 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff67ae825 in ?? () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#7  0x00007ffff67ae9b0 in wxGenericListCtrl::InsertItem(wxListItem&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#8  0x00007ffff67aeaa2 in wxGenericListCtrl::InsertItem(long, wxString const&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#9  0x0000000000514cb0 in AddIUFromHDBDialog::loadHDB(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#10 0x00000000005147ea in AddIUFromHDBDialog::TransferDataToWindow() ()
#11 0x00007ffff696513d in wxWindowBase::OnInitDialog(wxInitDialogEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#12 0x00007ffff60b91fe in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
    () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#13 0x00007ffff623f6e7 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#14 0x00007ffff623f7db in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) ()
   from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
```

**Comment by pjaaskel** [comment]
The above was for IU add, which crashes also. RF adding doesn't.

This is an alternative BT:
```
#0  __memcpy_sse2 () at ../sysdeps/x86_64/multiarch/../memcpy.S:201
#1  0x00007ffff3c1221a in std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_assign(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff3c12519 in std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::operator=(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x000000000046c937 in wxString::operator=(wxString const&) ()
#4  0x00000000005181fd in AddFUFromHDBDialog::loadHDB(HDB::HDBManager const&) ()
#5  0x000000000051783e in AddFUFromHDBDialog::TransferDataToWindow() ()
```
This is a no-debug build.

**Comment by pjaaskel** [comment]
This is with Ubuntu 16.04.

**Comment by pjaaskel** [comment]
Kubuntu more specifically.

**Comment by pjaaskel** [comment]
On my another Kubuntu 16.04 with LLVM built with assertions+release, the crash does not happen.

**Comment by pjaaskel** [comment]
After a few rebuilds, I cannot reproduce this anymore nor can anyone else, thus likely a dirty build.
